spring.application.name=orcapro

# TODOS OS DADOS DE ACESSO
# SÃO FORNECIDOS PELA FACULDADE

# Endereço do banco de dados
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Mostrar as instruções SQL
# executadas no banco de dados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret= ${JWT_SECRET}
jwt.expiration=86400000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update